version: "3.9"
services:
  steamcmd-eco:
    build:
      context: .
    image: steamcmd-eco:latest
    container_name: steamcmd-eco
    environment:
      - ECO_SERVER_PATH=${ECO_SERVER_PATH:-/eco}
    volumes:
      - eco_server:/eco
    ports:
      - 3000:3000
      - 3001:3001

volumes:
  eco_server:
    name: eco_server
    driver: local